#!/usr/bin/env python3
"""
Feishu notification module for price changes.
Sends interactive card messages to a Feishu group via webhook.
"""
import json
import os
import requests
from datetime import datetime

def get_webhook_url(config):
    """Resolve Feishu webhook URL: env var (CI/secrets) takes priority over config file."""
    return os.environ.get("FEISHU_WEBHOOK_URL") or config.get("settings", {}).get("feishu_webhook_url", "")

def format_price(price, currency):
    """Format price with currency symbol."""
    currency_symbols = {
        "MXN": "MXN$", "BRL": "R$", "COP": "COP$",
        "TRY": "TRY", "AED": "AED", "SAR": "SAR",
        "USD": "$", "EUR": "EUR",
    }
    sym = currency_symbols.get(currency, currency or "")
    if price is None:
        return "N/A"
    if isinstance(price, float) and price == int(price):
        price = int(price)
    return f"{sym} {price:,.0f}" if currency else f"{price:,.0f}"

def build_card(changes):
    """Build a Feishu interactive card for price changes."""
    total = len(changes)
    up = [c for c in changes if (c.get("change_pct") or 0) > 0]
    down = [c for c in changes if (c.get("change_pct") or 0) < 0]

    header_title = f"个护价格变动提醒 ({total} 条变动"
    if up:
        header_title += f", {len(up)} 涨价"
    if down:
        header_title += f", {len(down)} 降价"
    header_title += ")"

    elements = []

    for c in changes:
        pct = c.get("change_pct") or 0
        arrow = "UP" if pct > 0 else "DOWN" if pct < 0 else "="
        color_tag = "red" if pct > 0 else "green" if pct < 0 else "grey"

        old_str = format_price(c.get("old_price"), c.get("currency"))
        new_str = format_price(c.get("new_price"), c.get("currency"))

        content_lines = [
            f"**{c['product']}**",
            f"Category: {c.get('category', 'N/A')}  |  Market: {c['market']}  |  Platform: {c['platform']}",
            f"Price: ~~{old_str}~~ -> **{new_str}** ({arrow} {pct:+.1f}%)",
        ]
        if c.get("url"):
            content_lines.append(f"[View product]({c['url']})")

        elements.append({
            "tag": "div",
            "text": {"tag": "lark_md", "content": "\n".join(content_lines)},
        })
        elements.append({"tag": "hr"})

    elements.append({
        "tag": "note",
        "elements": [
            {"tag": "plain_text",
             "content": f"Auto-generated by Price Monitor | {datetime.now().strftime('%Y-%m-%d %H:%M')}"}
        ],
    })

    card = {
        "msg_type": "interactive",
        "card": {
            "header": {
                "title": {"tag": "plain_text", "content": header_title},
                "template": "red" if up and not down else "green" if down and not up else "blue",
            },
            "elements": elements,
        },
    }
    return card

def send_price_change_notifications(changes, config):
    """Send price change notifications to Feishu via webhook."""
    webhook_url = get_webhook_url(config)
    if not webhook_url:
        print("[NOTIFY] No Feishu webhook URL configured. Skipping notifications.")
        print(f"[NOTIFY] {len(changes)} changes would have been sent:")
        for c in changes:
            print(f"  - {c['product']} @ {c['market']}/{c['platform']}: "
                  f"{c['old_price']} -> {c['new_price']} ({c['change_pct']:+.1f}%)")
        return False

    card = build_card(changes)

    try:
        resp = requests.post(webhook_url, json=card, timeout=10)
        resp.raise_for_status()
        result = resp.json()
        if result.get("StatusCode") == 0 or result.get("code") == 0 or result.get("status") == "success":
            print(f"[NOTIFY] Successfully sent {len(changes)} price changes to Feishu.")
            return True
        else:
            print(f"[NOTIFY] Feishu API returned: {result}")
            return False
    except Exception as e:
        print(f"[NOTIFY] Error sending to Feishu: {e}")
        return False

def send_summary(all_checked, changes, config):
    """Send a summary even when no changes detected."""
    webhook_url = get_webhook_url(config)
    if not webhook_url:
        print("[NOTIFY] No webhook URL, skipping summary.")
        return False

    card = {
        "msg_type": "interactive",
        "card": {
            "header": {
                "title": {"tag": "plain_text",
                          "content": f"Price Monitor Daily Report ({len(changes)} changes)"},
                "template": "turquoise" if not changes else "blue",
            },
            "elements": [
                {"tag": "div", "text": {"tag": "lark_md",
                    "content": f"**Checked:** {all_checked} products\n**Changes:** {len(changes)}\n\n"
                               + ("No price changes detected today." if not changes else
                                  f"{len(changes)} products had price changes. See alert above.")}},
                {"tag": "note", "elements": [
                    {"tag": "plain_text",
                     "content": f"Auto-generated by Price Monitor | {datetime.now().strftime('%Y-%m-%d %H:%M')}"}
                ]},
            ],
        },
    }
    try:
        resp = requests.post(webhook_url, json=card, timeout=10)
        resp.raise_for_status()
        print(f"[NOTIFY] Summary sent to Feishu.")
        return True
    except Exception as e:
        print(f"[NOTIFY] Error sending summary: {e}")
        return False
